<?php
require_once __DIR__.'/config/db.php'; require_once __DIR__.'/includes/storefront.php';
if(session_status()===PHP_SESSION_NONE)session_start();
$message='';$messageType='';$slug=trim($_GET['store']??$_POST['store']??'');$company=null;
if($slug!==''){$s=$conn->prepare("SELECT * FROM companies WHERE storefront_slug=? LIMIT 1");$s->execute([$slug]);$company=$s->fetch();}
if(!$company){http_response_code(404);die('Please open registration from a valid company storefront.');}
if(!companyHasAccess($company)){http_response_code(403);die('This company storefront is currently unavailable.');}
if($_SERVER['REQUEST_METHOD']==='POST'){$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$password=$_POST['password']??'';$confirm=$_POST['confirm_password']??'';
 if($name===''||$email===''||$phone===''||$password===''){$message='Please fill in all fields.';$messageType='danger';}
 elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)){$message='Please enter a valid email address.';$messageType='danger';}
 elseif(strlen($password)<8){$message='Password must be at least 8 characters.';$messageType='danger';}
 elseif($password!==$confirm){$message='Passwords do not match.';$messageType='danger';}
 else{$s=$conn->prepare('SELECT id FROM users WHERE email=? LIMIT 1');$s->execute([$email]);if($s->fetchColumn()){$message='An account with this email already exists.';$messageType='danger';}else{$s=$conn->prepare("INSERT INTO users(company_id,name,email,phone,password,role,status) VALUES(?,?,?,?,?,'customer','active')");$s->execute([(int)$company['id'],$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT)]);$message='Account created successfully. You can now sign in.';$messageType='success';}}
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Create Account | <?=htmlspecialchars($company['company_name'])?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"></head><body class="bg-light"><?php include __DIR__.'/includes/loader.php';?><div class="container"><div class="row justify-content-center align-items-center" style="min-height:100vh"><div class="col-md-6 col-lg-5"><div class="card shadow border-0 rounded-4"><div class="card-body p-4 p-md-5"><div class="text-center mb-4"><div class="text-success fs-1"><i class="bi bi-basket2-fill"></i></div><h2 class="fw-bold mb-1">Create Account</h2><p class="text-muted mb-0">Join <?=htmlspecialchars($company['company_name'])?></p></div><?php if($message):?><div class="alert alert-<?=htmlspecialchars($messageType)?>"><?=htmlspecialchars($message)?></div><?php endif;?><form method="post"><input type="hidden" name="store" value="<?=htmlspecialchars($slug)?>"><div class="mb-3"><label class="form-label">Full Name</label><input name="name" class="form-control" required></div><div class="mb-3"><label class="form-label">Email Address</label><input type="email" name="email" class="form-control" required></div><div class="mb-3"><label class="form-label">Phone Number</label><input name="phone" class="form-control" required></div><div class="mb-3"><label class="form-label">Password</label><input type="password" name="password" class="form-control" minlength="8" required></div><div class="mb-4"><label class="form-label">Confirm Password</label><input type="password" name="confirm_password" class="form-control" minlength="8" required></div><button class="btn btn-success w-100">Create Account</button></form><div class="text-center mt-3"><a href="login.php?store=<?=urlencode($slug)?>">Already have an account? Sign in</a></div><div class="text-center mt-2"><a class="small text-muted" href="store.php?store=<?=urlencode($slug)?>">Back to store</a></div></div></div></div></div></div></body></html>
