<?php
require_once __DIR__.'/config/db.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/storefront.php';
$slug=trim($_GET['store']??'');
if($slug===''){http_response_code(404);die('Store not found.');}
$s=$conn->prepare("SELECT * FROM companies WHERE storefront_slug=? LIMIT 1");$s->execute([$slug]);$company=$s->fetch();
if(!$company){http_response_code(404);die('Store not found.');}
$available=companyHasAccess($company);
$cats=[];$products=[];$q=trim($_GET['q']??'');$category=(int)($_GET['category']??0);
if($available){
 $s=$conn->prepare("SELECT id,name FROM categories WHERE company_id=? AND status='active' ORDER BY name");$s->execute([$company['id']]);$cats=$s->fetchAll();
 $sql="SELECT p.id,p.name,p.description,p.price,p.stock,p.unit,p.image,c.name category_name,(SELECT pi.image FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.is_primary DESC,pi.sort_order,pi.id LIMIT 1) primary_image FROM products p LEFT JOIN categories c ON c.id=p.category_id AND c.company_id=p.company_id WHERE p.company_id=? AND p.status='active'";$params=[(int)$company['id']];
 if($q!==''){$sql.=" AND (p.name LIKE ? OR p.description LIKE ?)";$params[]="%$q%";$params[]="%$q%";} if($category>0){$sql.=" AND p.category_id=?";$params[]=$category;}$sql.=" ORDER BY p.created_at DESC";$s=$conn->prepare($sql);$s->execute($params);$products=$s->fetchAll();
}
function storeImg($p){return $p['primary_image'] ?: $p['image'];}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($company['company_name'])?> | Storefront</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><style>body{background:#f5f7f8}.store-hero{background:#071827;color:#fff}.logo{width:58px;height:58px;object-fit:cover;border-radius:14px;background:#fff}.product-card{background:#fff;border:1px solid #e8ecef;border-radius:16px;overflow:hidden;height:100%;box-shadow:0 5px 18px rgba(0,0,0,.04)}.thumb{width:100%;height:190px;object-fit:cover}.placeholder{height:190px;display:grid;place-items:center;background:#eef2f3;font-size:42px;color:#98a2aa}</style></head><body>
<nav class="navbar navbar-dark" style="background:#071827"><div class="container"><a class="navbar-brand fw-bold" href="store.php?store=<?=urlencode($slug)?>"><?=e($company['company_name'])?></a><div class="d-flex gap-2"><a class="btn btn-outline-light btn-sm" href="login.php?store=<?=urlencode($slug)?>">Login</a><a class="btn btn-success btn-sm" href="register.php?store=<?=urlencode($slug)?>">Create account</a></div></div></nav>
<section class="store-hero py-5"><div class="container d-flex align-items-center gap-3"><?php if(!empty($company['logo'])):?><img class="logo" src="<?=e($company['logo'])?>" alt="logo"><?php endif;?><div><h1 class="fw-bold mb-1"><?=e($company['company_name'])?></h1><p class="mb-0 opacity-75">Shop groceries from this store and get them delivered.</p></div></div></section>
<main class="container py-4"><?php if(!$available):?><div class="alert alert-warning">This storefront is temporarily unavailable. Please check back later.</div><?php else:?><form class="row g-2 mb-4"><input type="hidden" name="store" value="<?=e($slug)?>"><div class="col-md-7"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Search products..."></div><div class="col-md-3"><select class="form-select" name="category"><option value="0">All categories</option><?php foreach($cats as $c):?><option value="<?=(int)$c['id']?>" <?=$category===(int)$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-2 d-grid"><button class="btn btn-success">Search</button></div></form>
<div class="row g-4"><?php if(!$products):?><div class="col-12"><div class="bg-white rounded-4 p-5 text-center text-muted">No products found.</div></div><?php endif;?><?php foreach($products as $p):?><div class="col-xl-3 col-lg-4 col-md-6"><div class="product-card"><?php if(storeImg($p)):?><img class="thumb" src="<?=e(storeImg($p))?>" alt="<?=e($p['name'])?>"><?php else:?><div class="placeholder"><i class="bi bi-image"></i></div><?php endif;?><div class="p-3"><small class="text-muted"><?=e($p['category_name']??'Uncategorized')?></small><h5 class="fw-bold mt-1"><?=e($p['name'])?></h5><div class="text-success fw-bold fs-5">GH₵<?=number_format($p['price'],2)?></div><p class="small text-muted mb-3"><?=e(number_format($p['stock'],2).' '.$p['unit'].' available')?></p><a class="btn btn-success w-100" href="register.php?store=<?=urlencode($slug)?>">Sign up to order</a></div></div></div><?php endforeach;?></div><?php endif;?></main></body></html>
